[package]
name = "zeta"
version = "0.1.0"
repository = "https://github.com/nwrenger/zeta"
authors = ["nils@wrenger.net"]
description = "A performant file editor with extensive shortcuts"
license = "MIT"
edition = "2021"
keywords = ["editor", "file", "shortcuts"]
categories = ["command-line-utilities", "text-editors"]

[dependencies]
clippers = "0.1.2"
cursive = "0.20.0"
