[package]
name = "omega"
version = "0.2.6"
repository = "https://github.com/nwrenger/omega"
documentation = "https://github.com/nwrenger/omega"
readme = "README.md"
authors = ["nils@wrenger.net"]
description = "A performant terminal-based project editor with extensive shortcuts"
license = "MIT"
edition = "2021"
keywords = ["editor", "file", "project", "shortcuts", "tool"]
categories = ["command-line-utilities", "text-editors"]
rust-version = "1.70.0"

[profile.release]
lto = "thin"
opt-level = 3
codegen-units = 1
strip = true

[dependencies]
clippers = "0.1.2"
cursive = { version = "0.20.0", default-features = false, features = [
    "crossterm-backend",
] }
cursive_buffered_backend = "0.6.1"
cursive_tree_view = "0.8.0"
unicode-segmentation = "1.11.0"
unicode-width = "0.1.11"
