[package]
name = "omega"
version = "0.1.0"
repository = "https://github.com/nwrenger/omega"
documentation = "https://github.com/nwrenger/omega"
readme = "README.md"
authors = ["nils@wrenger.net"]
description = "A performant terminal-based file editor with extensive shortcuts"
license = "MIT"
edition = "2021"
keywords = ["editor", "file", "shortcuts", "tool"]
categories = ["command-line-utilities", "text-editors"]

[dependencies]
clippers = "0.1.2"
cursive = "0.20.0"
