name: Build

on:
  release:
    types: [published]
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build-rust:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            exe: omega
          - os: macos-latest
            exe: omega

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build -r
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.exe }}
          path: target/release/${{ matrix.exe }}
      - name: Rename
        run: cp target/release/${{ matrix.exe }} ${{ matrix.os }}-${{ matrix.exe }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.os }}-${{ matrix.exe }}
